### ISSUE TITLE
how to rebase

### ISSUE THREAD

**Issue by daymos** [smooth-operators-fac/currency-map#10]
sam, i just tested the old rebase against the new and there seem to be non difference in the outcome.

**Comment by g-sam** [comment]
loathing/loving out loud. can you push to branch and i will test?

**Comment by daymos** [comment]
ok I just calculated by hand and  found my error, the math fix was right.

**Comment by daymos** [comment]
I guess last week I fixed the bug in your code, this time it was your turn :)
