### ISSUE TITLE
Modifying prototypes

### ISSUE THREAD

**Issue by eliasmalik** [smooth-operators-fac/currency-map#18]
For this project it doesn't really matter, but in general, it's often considered bad practice to modify native prototypes like you've done with the Date object.

See: [1](https://www.nczonline.net/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/), [2](http://stackoverflow.com/questions/6223449/why-is-it-frowned-upon-to-modify-javascript-objects-prototypes), [3](http://stackoverflow.com/questions/14034180/why-is-extending-native-objects-a-bad-practice)

However, there are more nuanced opinions: [1](http://sugarjs.com/native), [2](http://perfectionkills.com/extending-native-builtins/)

**Comment by daymos** [comment]
have refactored with new MyDate constructor not to override the natives,  first 3 articles were pretty convincing.
Also added promises. If you have time to have look at it, any comments are welcomed.
