### ISSUE TITLE
More descriptive method names

### ISSUE THREAD

**Issue by matthewglover** [smooth-operators-fac/currency-map#20]
Some of your method names are perhaps a little unclear.

For example: currencyOBJ.urls - takes a date and returns a single url for a specific date. perhaps buildUrlForDate would be clearer.

Similarly for the Date.subDays method - it would be clearer if were called subtractDays.

**Comment by daymos** [comment]
just rewrote with promises and renamed most function to make it more readable. If you have time to have a look any comments are welcomed

**Comment by matthewglover** [comment]
Looks great! New names make it so much easier to follow code! Refactor with Promise.all is  perfect example of why Promises are so cool! 👍

**Comment by daymos** [comment]
Thanks, yes promises are really cool. Next step is to try the same with
generators and see how it looks!
Il 26/giu/2016 16:00 "Matthew Glover" notifications@github.com ha scritto:
