### ISSUE TITLE
ES6 or not?

### ISSUE THREAD

**Issue by otajor** [smooth-operators-fac/currency-map#25]
https://github.com/smooth-operators-fac/currency-map/blob/master/js/currencyAPI.js#L49-L54

I like your use of reduce here. 👍  Might be worth having a mini code review within the group (if you haven't already) to make sure everyone understands how this bit of code works and what it's doing.

Also, it would be good to see consistency in your use of ES6 arrow functions. You seem to have used arrow functions for all anonymous functions but normal ES5 function statements for other functions and methods. Any reason for that?

**Comment by daymos** [comment]
If I didn't use arrow functions for the callbacks the code wouldn't work, unless I use 'Bind()'
Are you suggesting we should use them for defining methods as well or the new ES6 shorthand for methods?

**Comment by otajor** [comment]
Ah OK that's why you did it, fair enough. Yes either of those options. I personally just use arrow functions everywhere but it's up to you.

**Comment by g-sam** [comment]
Can we agree to prefer arrow functions unless there is some practical use for a mutable `this`? (side note: is there, ever such a need?)

**Comment by daymos** [comment]
what do you mean with 'mutable this'?
if you want you function to have its own this you cannot use an arrow function. In an object they are interchangeble when you define a method but its kind of an exeption. I dont know enough to decide on this, best approach could be to set on shared linter configuration. Matt was using the one from airbnbn for his team.

**Comment by g-sam** [comment]
I mean unbound. I think we're on the same page but the way I would put it is to say that arrow functions always have their own `this` -- the `this` they had where they were defined. They are 'bound' to this `this`.

There are some situations where NOT having an arrow function makes for simpler code. e.g.

``` javascript
var obj = {
    addMethod: function(callback){
        this.callback = callback
    }
}
```

Here you actually want `callback` to be unbound so it can take `obj` as its `this`. Otherwise you have to do something like `this.callback = callback.bind(this)`, right? Maybe someone can think of a more practical example?!

**Comment by g-sam** [comment]
Just noticed the most obvious place where arrow functions are BAD is assigning a new method to an object:

``` javascript
var obj = {
val: 10
}
obj.method = () => {return this.val}.
```

The arrow function will bind `this` to global, where more likely you want it bound to the object.

**Comment by daymos** [comment]
as far as i know in ES6 the suggested syntax for method is so:

```
var obj = {
val: 10
},
methodName() {//do something}
}
```

**Comment by daymos** [comment]
unless oturnermajor advises us against it, what do you think to try to conform to this:
https://github.com/airbnb/javascript#ecmascript-6-styles

**Comment by g-sam** [comment]
yes, the airbnb guidelines look fine to me.
there's some typo(s) in your ES6 example--can't see what you mean.

**Comment by daymos** [comment]
sorry just fixed. thats what airbnb suggest to use inside object.
Btw just rewrote everything using promises and refactor according that guide more or less.

**Comment by otajor** [comment]
@daymos @g-sam Yep having style guidelines is a great idea, it doesn't matter much which ones you pick so long as everyone in the team sticks to them. AirBnB's ones are great. Put them in your .eslintrc so that your linter will enforce them 👍

**Comment by otajor** [comment]
(Gonna close this now 👍 )

**Comment by daymos** [comment]
👍
