### ISSUE TITLE
server

### ISSUE THREAD

**Issue by g-sam** [smooth-operators-fac/currency-map#35]
I'm going to at least start making a server for this. partly for practice, partly so we can store our results!

I will try to push regularly to `server` branch so you can see what I'm doing.

**Comment by daymos** [comment]
ok cool. if you are up for pair programming at some point let me know. I just met a guy who work for 8th light and they do a lot of it in their daily work

**Comment by g-sam** [comment]
you mean remote pairing? I'm just making lunch but can do in a bit...

**Comment by daymos** [comment]
I mean at some point in the weekend or week. if we do it we should agree on what we are going to do beforehand I think

**Comment by daymos** [comment]
sorry remote pairing yes

**Comment by g-sam** [comment]
my plan for today was to
- set up the server (basically done)
- transfer api requests for historic data to server and increase the number of samples (and store responses). also put a daily request for today's rates to the server. this will be data that can be used if the call limit is exceeded by client-side calls. (or something like that)
- get to the bottom of the math issue
- improve the selectbox
- address the other issues

if you want to pair for any of this (or if you have other ideas), just let me know. I'll be ready in about 15 mins.

**Comment by daymos** [comment]
today I'll pass, if you want tomorrow untill 2 pm Im available, or we could do one evening in the next week. Monday and Thuesday I forecast it will be still project days!!

**Comment by g-sam** [comment]
I'm available now!
